branch-defaults:
  elasticbeanstalk:
    environment: dshop-dev
    group_suffix: null
global:
  application_name: Dshop
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: pymasters-zappa
  repository: null
  sc: git
  workspace_type: Application
