# Generated by Django 4.2.7 on 2024-04-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0024_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_sum',
        ),
    ]
