[tool.poetry]
name = "dshop"
version = "0.1.0"
description = "Django E-shop project"
authors = ["Akademia IT"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"
python-decouple = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
